Request to merge Feature/update-delete into dev branch
flemton/vet-clinic pull request #2
Opened 2023-06-16 20:33 UTC by flemton

In this PR the following commits were made to answer questions from the [exercise: query and update animals table](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md#vet-clinic-database-query-and-update-animals-table)

- [Add species to animals table](https://github.com/flemton/vet-clinic/commit/1f4cfd47b85761e1cc7c13955a6f6c0c5021539d)
<img width="626" alt="Screenshot 2023-06-16 at 2 10 10 AM" src="https://github.com/flemton/vet-clinic/assets/36508436/9cbe453b-cf8b-4730-aa21-de38c107f026">

- [Add transactions](https://github.com/flemton/vet-clinic/commit/0df45970703498692609f810ab894238de9e83b2)
<img width="609" alt="Screenshot 2023-06-16 at 1 49 15 AM" src="https://github.com/flemton/vet-clinic/assets/36508436/07f4b01f-a68c-470b-897e-a8ed0124d61f">
<img width="626" alt="Screenshot 2023-06-16 at 2 10 10 AM" src="https://github.com/flemton/vet-clinic/assets/36508436/9dfe0dfc-ad9c-4dc1-a3eb-9b80963cd63c">

- [Use aggregate functions](https://github.com/flemton/vet-clinic/commit/fce847f2e2afe2e14f4967cdeef53bc6f0673a7d)
<img width="307" alt="Screenshot 2023-06-16 at 7 53 05 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/0969040d-3f83-42a0-9e2a-878e7c18e2db">
<img width="490" alt="Screenshot 2023-06-16 at 7 53 50 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/1c718ed8-a391-4467-b6ce-4f549558f2b3">
<img width="350" alt="Screenshot 2023-06-16 at 7 54 39 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/81469f29-5734-4ddb-84f7-518e9cef5a99">
<img width="567" alt="Screenshot 2023-06-16 at 7 58 20 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/e2b52eb2-caf8-4320-8b88-5c2480e15cda">
<img width="535" alt="Screenshot 2023-06-16 at 8 00 40 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/5de06bdc-85f4-41c4-9b46-ba957cd1ef09">
<img width="535" alt="Screenshot 2023-06-16 at 8 01 33 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/9c2b6432-a95f-4db7-89c7-fe78354747f0">
<img width="535" alt="Screenshot 2023-06-16 at 8 02 02 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/2eeb3175-b8ab-415b-8434-a70c6ea88422">
<img width="535" alt="Screenshot 2023-06-16 at 8 02 31 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/c4ddc2e5-3ef9-4fba-89ff-b3656f22c219">
<img width="688" alt="Screenshot 2023-06-16 at 8 09 07 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/ded23d27-0839-4d56-af35-18b873bcad19">
<img width="659" alt="Screenshot 2023-06-16 at 8 09 22 PM" src="https://github.com/flemton/vet-clinic/assets/36508436/7cf8b5b0-6aa6-42b2-aee6-4e6fd1a35e2c">

2023-06-16 21:05 UTC, 1GORDON requested changes
##
## Hi @flemton ✋

Good job so far!

## Highlights!
- Great use of Gitflow ✔️ 
- Good commit messages ✔️
- Descriptive Pull request ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly fix the broken issues link to make your readme file more professional.
- [ ] Kindly ensure all the screenshots for all queries are added to the pull request before you resubmit for review. You seem to have missed a number of screenshots. Kindly take a closer look at the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md).

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 21:05 UTC, 1GORDON commented on schema.sql
>  );
Great job @flemton 🤝

- [ ] As stated in the project requirements, kindly add a new column called species with a string type. Ensure this command is added to the `schema.sql` file as well.
   `ALTER TABLE animals ADD species varchar(255);`

2023-06-16 21:05 UTC, 1GORDON commented on queries.sql
> +
Great job @flemton 🤝

- [x] As stated in the project requirements, Inside a transaction update the `animals` table by setting the species column to unspecified. Verify that the change was made. Then roll back the change and verify that the species columns went back to the state before the transaction. Kindly add this transaction to the `queries.sql` file
- [x] Also remember to add a screenshot of this transaction to your pull request.

2023-06-16 21:05 UTC, 1GORDON commented on queries.sql
> +
Great job @flemton 🤝

- [x] As stated in the project requirements, Inside a transaction delete all records in the `animals` table, then roll back the transaction. Kindly add this transaction to the `queries.sql` file.

2023-06-16 21:05 UTC, 1GORDON commented on queries.sql
> +COMMIT;
Great job @flemton 🤝

- [x] As stated in the project requirements, kindly add the results of this transaction to your pull request.

2023-06-16 22:23 UTC, flemton commented on queries.sql
> +
Dear @1GORDON, please this transaction was done and it is the first screenshot under the 'Add transactions' list in the PR description.

2023-06-16 22:28 UTC, flemton commented on queries.sql
> +
Dear @1GORDON, please this transaction was done and it is the first screenshot under the 'Add transactions' list in the PR description.

2023-06-16 22:30 UTC, flemton commented on queries.sql
> +
Hi @1GORDON, this is done and it is the first screenshot of the PR description now, thanks.

2023-06-16 22:32 UTC, flemton commented on queries.sql
> +COMMIT;
Dear @1GORDON, this is done and is now the last screenshot

2023-06-16 23:23 UTC, 1GORDON requested changes
##
## Hi @flemton ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️
- Professional Readme file ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 23:23 UTC, 1GORDON commented on queries.sql
> +
Great job @flemton 🤝

- [ ] As stated in the project requirements, Inside a transaction update the `animals` table by setting the species column to unspecified. Verify that the change was made. Then roll back the change and verify that the species columns went back to the state before the transaction. Kindly add this transaction to the `queries.sql` file.

2023-06-17 00:36 UTC, Reem-lab approved these changes
# Hi @flemton,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights
- [ ] Great job on the funtionality 💯
- [ ] Followed Gitflow 🔥
- [ ] No Linters error ✅
- [ ] Kudos wokring on the requested changes⭐


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 00:43 UTC, merged